export enum ReduxConstants {
    /* Disk */
    REQUEST_DISK_INFO = 'REQUEST_DISK_INFO',
    RECEIVE_DISK_INFO = 'RECEIVE_DISK_INFO',
    RECEIVE_DISK_CONNECT = 'RECEIVE_DISK_CONNECT',
    RECEIVE_DISK_DISCONNECT = 'RECEIVE_DISK_DISCONNECT'
}